name: Documentation

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hendrikmuhs/ccache-action@v1
        with:
          key: build-${{ hashFiles('**/deps/meson.build') }}
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          sudo apt install doxygen
          pip install meson ninja jinja2 Pygments libgs
      - name: Setup
        run: meson setup build
      - name: Generate docs
        run: ninja docs -C build
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs/html
