name: Install

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-ubuntu:
    name: Check if install works on Ubuntu (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hendrikmuhs/ccache-action@v1
        with:
          key: build-${{ hashFiles('**/deps/meson.build') }}
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install meson ninja
      - name: Setup
        run: meson setup build
      - name: Build and install library
        run: ninja install -C build -v
      - name: Test installed library
        run: ninja test -C build -DBUILD_WITH_INSTALLED -v
  build-macos:
    name: Check if install works on MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hendrikmuhs/ccache-action@v1
        with:
          key: build-${{ hashFiles('**/deps/meson.build') }}
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install meson ninja
      - name: Setup
        run: meson setup build
      - name: Build and install library
        run: ninja install -C build -v
      - name: Test installed library
        run: ninja test -C build -DBUILD_WITH_INSTALLED -v
  build-windows:
    name: Check if install works on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hendrikmuhs/ccache-action@v1
        with:
          key: build-${{ hashFiles('**/deps/meson.build') }}
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install meson ninja
      - name: Setup
        run: meson setup build
      - name: Build and install library
        run: ninja install -C build -v
      - name: Test installed library
        run: ninja test -C build -DBUILD_WITH_INSTALLED -v