name: Install

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install dependencies
        run: |
          sudo apt install ninja-build g++-10

      - name: build and install library
        run: |
          CXX=g++-10 cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja -DUSE_CCACHE=True -DUSE_SANITIZER="Address:Undefined:Leak"
          sudo cmake --build build --target install
          rm -rf build

      - name: configure
        run: CXX=g++-10 cmake -Stest -Bbuild -GNinja -DTEST_INSTALLED_VERSION=1

      - name: build
        run: cmake --build build --config Debug -j4

      - name: test
        run: |
          cd build
          ctest --build-config Debug
