name: Tests

on:
  push:
    branches:
      - master
      - develop
      - feature/*
  pull_request:
    branches:
      - master
      - develop
      - feature/*

jobs:
  build-ubuntu:
    name: Run tests on Ubuntu (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hendrikmuhs/ccache-action@v1
        with:
          key: build-${{ hashFiles('**/deps/meson.build') }}
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install meson ninja
      - name: Setup
        run: |
          meson setup build
          meson configure --buildtype debugoptimized --debug -DENABLE_TESTS=true -Db_sanitize=address,undefined build
      - name: Build library
        run: ninja -C build -v
      - name: Run tests
        run: ninja test -C build
      - name: Collect code coverage
        run: |
          ninja coverage-html -C build
          bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  build-macos:
    name: Run tests on MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hendrikmuhs/ccache-action@v1
        with:
          key: build-${{ hashFiles('**/deps/meson.build') }}
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install meson ninja
      - name: Setup
        run: |
          meson setup build
          meson configure --buildtype debugoptimized --debug -DENABLE_TESTS=true -Db_sanitize=address,undefined build
      - name: Build library
        run: ninja -C build -v
      - name: Run tests
        run: ninja test -C build
  build-windows:
    name: Run tests on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hendrikmuhs/ccache-action@v1
        with:
          key: build-${{ hashFiles('**/deps/meson.build') }}
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install meson ninja
      - name: Setup
        run: |
          meson setup build
          meson configure --buildtype debugoptimized --debug -DENABLE_TESTS=true -Db_sanitize=address,undefined build
      - name: Build library
        run: ninja -C build -v
      - name: Run tests
        run: ninja test -C build