name: Windows

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hendrikmuhs/ccache-action@v1
        with:
          key: build-${{ hashFiles('**/deps/meson.build') }}
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install meson ninja
      - name: Setup
        run: meson setup build
      - name: Build and run tests
        run: ninja test -C build -v -Db_sanitize=address,undefined

